<?php
/**
 * Options header of theme options.
 */
return array(
	'id'             => 'header',
	'title'          => esc_html__( 'Header', 'edupro' ),
	'settings_pages' => 'theme-options',
	'tab'            => 'header',
	'tabs'           => array(
		'header-style' => array(
			'label' => esc_html__( 'Header Style', 'edupro' ),
			'icon'  => 'dashicons-category',
		),
		'header-color' => array(
			'label' => esc_html__( 'Header Color', 'edupro' ),
			'icon'  => 'dashicons-category',
		),
		'header-megamenu'  => array(
			'label' => esc_html__( 'Mega Menu', 'edupro' ),
			'icon'  => 'dashicons-category',
		),
	),
	'fields'         => array(
		// HEADER STYLE DEFAULT
		array(
			'name'    => esc_html__( 'Header style', 'edupro' ),
			'id'      => 'header_style',
			'type'    => 'image_select',
			'options' => array(
				'1' => get_template_directory_uri() . '/img/header/header-s1.png',
				'2' => get_template_directory_uri() . '/img/header/header-s2.png',
				'3' => get_template_directory_uri() . '/img/header/header-s3.png',
				'4' => get_template_directory_uri() . '/img/header/header-s4.png',
				'5' => get_template_directory_uri() . '/img/header/header-s5.png',
				'6' => get_template_directory_uri() . '/img/header/header-s6.png',
			),
			'std'     => '1',
			'tab'     => 'header-style',
			'class'   => 'style-header img-full',
		),
		array(
			'name' => esc_html__( 'Image Banner', 'edupro' ),
			'id'   => 'header_banner',
			'type' => 'file_input',
			'std'  => esc_url( get_template_directory_uri() . '/img/banner-header.jpg' ),
			'tab'     => 'header-style',
			'visible' => array( 'header_style', '=', '4' ),
		),
		array(
			'id'   => 'is_sticky',
			'name' => esc_html__( 'Fix Top Header on Scroll?', 'edupro' ),
			'type' => 'checkbox',
			'std'  => '1',
			'tab'     => 'header-style',
		),
		array(
			'name'     => esc_html__( 'Show Search | Cart or Socials', 'edupro' ),
			'id'       => "cart_search_social",
			'type'     => 'select',
			'options'  => array(
				'0' => esc_html__( 'Default', 'edupro' ),
				'1' => esc_html__( 'Search | Cart', 'edupro' ),
				'2' => esc_html__( 'Socials', 'edupro' ),
			),
			'multiple' => false,
			'std'      => '1',
			'tab'     => 'header-style',
		),
		array(
			'name'     => esc_html__( 'Font Family', 'edupro' ),
			'id'       => "font_family_menu",
			'type'     => 'select',
			'options'  => edupro_all_fonts(),
			'multiple' => false,
			'std'      => '12',
			'tab'     => 'header-style',
		),
		array(
			'name'     => esc_html__( 'Font size menu', 'edupro' ),
			'id'       => "font_size_menu",
			'type'     => 'select',
			'options'  => EduPro_Option::list_font_size(),
			'multiple' => false,
			'std'      => '15',
			'tab'     => 'header-style',
		),
		array(
			'name'     => esc_html__( 'Font size sub menu', 'edupro' ),
			'id'       => "font_size_sub_menu",
			'type'     => 'select',
			'options'  => EduPro_Option::list_font_size(),
			'multiple' => false,
			'std'      => '12',
			'tab'     => 'header-style',
		),
		array(
			'name'     => esc_html__( 'Font Weight', 'edupro' ),
			'id'       => "font_weight_menu",
			'type'     => 'select',
			'options'  => array(
				'normal'  => 'Normal',
				'bold'    => 'Bold',
				'bolder'  => 'Bolder',
				'lighter' => 'Lighter',
				'100'     => '100',
				'200'     => '200',
				'300'     => '300',
				'400'     => '400',
				'500'     => '500',
				'600'     => '600',
				'700'     => '700',
				'800'     => '800',
				'900'     => '900'
			),
			'multiple' => false,
			'std'      => 'normal',
			'tab'     => 'header-style',
		),
		array(
			'name'     => esc_html__( 'Text Transform', 'edupro' ),
			'id'       => "txt_transform_menu",
			'type'     => 'select',
			'options'  => array(
				'none' => esc_html__( 'None', 'edupro' ),
				'capitalize' => esc_html__( 'Capitalize', 'edupro' ),
				'lowercase' => esc_html__( 'Lowercase', 'edupro' ),
				'uppercase' => esc_html__( 'Uppercase', 'edupro' ),
			),
			'multiple' => false,
			'std'      => 'uppercase',
			'tab'     => 'header-style',
		),
		
		array(
			'name'     => esc_html__( 'Font Style', 'edupro' ),
			'id'       => "font_style_menu",
			'type'     => 'select',
			'options'  => array(
				'normal' => esc_html__( 'Normal', 'edupro' ),
				'italic' => esc_html__( 'Italic', 'edupro' ),
				'oblique' => esc_html__( 'Oblique', 'edupro' ),
			),
			'multiple' => false,
			'std'      => 'normal',
			'tab'     => 'header-style',
		),
		/*===*/
		array(
			'id'      => 'bg_header_color',
			'name'    => esc_html__( 'Background Color', 'edupro' ),
			'type'    => 'color',
			'section' => 'colors',
			'tab'     => 'header-color',
		),
		array(
			'id'      => 'txt_menu_header_color',
			'name'    => esc_html__( 'Text Color', 'edupro' ),
			'type'    => 'color',
			'section' => 'colors',
			'tab'     => 'header-color',
		),
		array(
			'id'      => 'hover_txt_menu_header_color',
			'name'    => esc_html__( 'Text Hover Color', 'edupro' ),
			'type'    => 'color',
			'section' => 'colors',
			'tab'     => 'header-color',
		),
		array(
			'id'      => 'icon_menu_header_color',
			'name'    => esc_html__( 'Icon Color', 'edupro' ),
			'type'    => 'color',
			'section' => 'colors',
			'tab'     => 'header-color',
		),
		array(
			'id'      => 'hover_icon_menu_header_color',
			'name'    => esc_html__( 'Icon Hover Color', 'edupro' ),
			'type'    => 'color',
			'section' => 'colors',
			'tab'     => 'header-color',
		),
		array(
			'id'      => 'cart_item_color',
			'name'    => esc_html__( 'Cart Item Color', 'edupro' ),
			'type'    => 'color',
			'section' => 'colors',
			'tab'     => 'header-color',
		),
		array(
			'id'      => 'header_line_color',
			'name'    => esc_html__( 'Header Bottom Line Color', 'edupro' ),
			'type'    => 'color',
			'section' => 'colors',
			'tab'     => 'header-color',
		),
		array(
			'type' => 'heading',
			'name' => esc_html__( 'Sticky Menu', 'edupro' ),
			'tab'  => 'header-color',
		),
		array(
			'id'      => 'sticky_bg_menu_header_color',
			'name'    => esc_html__( 'Background Color', 'edupro' ),
			'type'    => 'color',
			'section' => 'colors',
			'tab'     => 'header-color',
		),
		array(
			'id'      => 'sticky_txt_menu_header_color',
			'name'    => esc_html__( 'Text Color', 'edupro' ),
			'type'    => 'color',
			'section' => 'colors',
			'tab'     => 'header-color',
		),
		array(
			'id'      => 'bg_sub_menu_header_color',
			'name'    => esc_html__( 'Background sub menu header', 'edupro' ),
			'type'    => 'color',
			'section' => 'colors',
			'tab'     => 'header-color',
		),
		array(
			'type' => 'heading',
			'name' => esc_html__( 'Submenu', 'edupro' ),
			'tab'  => 'header-color',
		),
		array(
			'id'      => 'border_sub_menu_header_color',
			'name'    => esc_html__( 'Border Color', 'edupro' ),
			'type'    => 'color',
			'section' => 'colors',
			'tab'     => 'header-color',
		),
		array(
			'id'      => 'txt_sub_menu_header_color',
			'name'    => esc_html__( 'Text Color', 'edupro' ),
			'type'    => 'color',
			'section' => 'colors',
			'tab'     => 'header-color',
		),
		array(
			'id'      => 'hover_txt_sub_menu_header_color',
			'name'    => esc_html__( 'Text Hover Color', 'edupro' ),
			'type'    => 'color',
			'section' => 'colors',
			'tab'     => 'header-color',
		),
		array(
			'name'     => esc_html__( 'Mega Menu option', 'edupro' ),
			'id'       => "megamenu_option",
			'type'     => 'select',
			'options'  => array(
				'0' => esc_html__( 'Mega Menu Default', 'edupro' ),
				'1' => esc_html__( 'Max Mega Menu', 'edupro' ),
			),
			'multiple' => false,
			'std'      => '0',
			'tab'     => 'header-megamenu',
		),
		array(
			'id'      => 'sb_left_mega_color',
			'name'    => esc_html__( 'Left Pane Background', 'edupro' ),
			'type'    => 'color',
			'section' => 'colors',
			'tab'     => 'header-megamenu',
			'visible' => array( 'megamenu_option', '=', '0' ),
		),
		array(
			'id'      => 'sb_right_mega_color',
			'name'    => esc_html__( 'Right Pane Background', 'edupro' ),
			'type'    => 'color',
			'section' => 'colors',
			'tab'     => 'header-megamenu',
			'visible' => array( 'megamenu_option', '=', '0' ),
		),
		array(
			'id'      => 'sb_line_mega_color',
			'name'    => esc_html__( 'Separation Line Color', 'edupro' ),
			'type'    => 'color',
			'section' => 'colors',
			'tab'     => 'header-megamenu',
			'visible' => array( 'megamenu_option', '=', '0' ),
		),
		array(
			'id'      => 'txt_left_mega_color',
			'name'    => esc_html__( 'Text Color In The Left Pane', 'edupro' ),
			'type'    => 'color',
			'section' => 'colors',
			'tab'     => 'header-megamenu',
			'visible' => array( 'megamenu_option', '=', '0' ),
		),
		array(
			'id'      => 'hover_txt_left_mega_color',
			'name'    => esc_html__( 'Text Hover Color In The Left Pane', 'edupro' ),
			'type'    => 'color',
			'section' => 'colors',
			'tab'     => 'header-megamenu',
			'visible' => array( 'megamenu_option', '=', '0' ),
		),
		array(
			'id'      => 'bg_active_txt_left_mega',
			'name'    => esc_html__( 'Background Color For Selected Category', 'edupro' ),
			'type'    => 'color',
			'section' => 'colors',
			'tab'     => 'header-megamenu',
			'visible' => array( 'megamenu_option', '=', '0' ),
		),
		array(
			'id'      => 'active_txt_left_mega',
			'name'    => esc_html__( 'Text Color For Selected Category', 'edupro' ),
			'type'    => 'color',
			'section' => 'colors',
			'tab'     => 'header-megamenu',
			'visible' => array( 'megamenu_option', '=', '0' ),
		),
		array(
			'id'      => 'title_right_sb',
			'name'    => esc_html__( 'Post Title Color', 'edupro' ),
			'type'    => 'color',
			'section' => 'colors',
			'tab'     => 'header-megamenu',
			'visible' => array( 'megamenu_option', '=', '0' ),
		),
		array(
			'id'      => 'date_item_right_sb',
			'name'    => esc_html__( 'Date Color', 'edupro' ),
			'type'    => 'color',
			'section' => 'colors',
			'tab'     => 'header-megamenu',
			'visible' => array( 'megamenu_option', '=', '0' ),
		),
		array(
			'id'      => 'header_mega_date',
			'name'    => esc_html__( 'Hide Post Date', 'edupro' ),
			'type'    => 'checkbox',
			'tab'     => 'header-megamenu',
			'visible' => array( 'megamenu_option', '=', '0' ),
		),
		array(
			'id'      => 'off_uppercase_cat_mega',
			'name'    => esc_html__( 'Turn Off Uppercase Posts Title', 'edupro' ),
			'type'    => 'checkbox',
			'tab'     => 'header-megamenu',
			'visible' => array( 'megamenu_option', '=', '0' ),
		),
		array(
			'id'      => 'title_maxmega_color',
			'name'    => esc_html__( 'Title color', 'edupro' ),
			'type'    => 'color',
			'section' => 'colors',
			'tab'     => 'header-megamenu',
			'visible' => array( 'megamenu_option', '=', '1' ),
		),
		array(
			'id'      => 'hover_title_maxmega_color',
			'name'    => esc_html__( 'Hover title color', 'edupro' ),
			'type'    => 'color',
			'section' => 'colors',
			'tab'     => 'header-megamenu',
			'visible' => array( 'megamenu_option', '=', '1' ),
		),
		array(
			'id'      => 'txt_maxmega_color',
			'name'    => esc_html__( 'Text color', 'edupro' ),
			'type'    => 'color',
			'section' => 'colors',
			'tab'     => 'header-megamenu',
			'visible' => array( 'megamenu_option', '=', '1' ),
		),
		array(
			'id'      => 'bg_maxmega_color',
			'name'    => esc_html__( 'Background color', 'edupro' ),
			'type'    => 'color',
			'section' => 'colors',
			'tab'     => 'header-megamenu',
			'visible' => array( 'megamenu_option', '=', '1' ),
		),
		array(
			'id'      => 'line_maxmega_color',
			'name'    => esc_html__( 'Line color', 'edupro' ),
			'type'    => 'color',
			'section' => 'colors',
			'tab'     => 'header-megamenu',
			'visible' => array( 'megamenu_option', '=', '1' ),
		),
	),
);
