<?php
/**
 * Option Woocommerce
 */
return array(
	'id'             => 'woo',
	'title'          => esc_html__( 'WooCommerce', 'edupro' ),
	'settings_pages' => 'theme-options',
	'tab'            => 'woo',
	'tabs'           => array(
		'woo-archive' => array(
			'label' => esc_html__( 'Archive', 'edupro' ),
			'icon'  => 'dashicons-category',
		),
		'woo-single'  => array(
			'label' => esc_html__( 'Single', 'edupro' ),
			'icon'  => 'dashicons-admin-post',
		),
	),
	'tab_style'      => 'box',
	'tab_wrapper'    => true,
	'fields'         => array(
		array(
			'name' => esc_html__( 'Header Image', 'edupro' ),
			'id'   => 'woo_header_image',
			'type' => 'file_input',
			'tab'  => 'woo-archive',
		),
		array(
			'name'    => esc_html__( 'Sidebar Layout', 'edupro' ),
			'id'      => 'woo_layout',
			'type'    => 'image_select',
			'options' => array(
				'sidebar-left'  => 'http://i.imgur.com/Y2sxQ2R.png',
				'sidebar-right' => 'http://i.imgur.com/h7ONxhz.png',
				'no-sidebar'    => 'http://i.imgur.com/m7oQKvk.png',
			),
			'tab'     => 'woo-archive',
			'std'     => 'sidebar-left',
		),
		array(
			'id'   => 'woo_hidden_filter',
			'name' => esc_html__( 'Hide Shopping Cart Filter?', 'edupro' ),
			'type' => 'checkbox',
			'tab'  => 'woo-archive',
		),
		array(
			'id'   => 'woo_hidden_icon_link',
			'name' => esc_html__( 'Hide Link Icon On Hover?', 'edupro' ),
			'type' => 'checkbox',
			'tab'  => 'woo-archive',
		),
		array(
			'id'   => 'woo_hidden_sale',
			'name' => esc_html__( 'Hide Sale Badge?', 'edupro' ),
			'type' => 'checkbox',
			'tab'  => 'woo-archive',
		),
		array(
			'name'     => esc_html__( 'Page Navigation Alignment', 'edupro' ),
			'id'       => 'woo_paging_align',
			'type'     => 'select',
			'options'  => array(
				'left'   => esc_html__( 'Left', 'edupro' ),
				'center' => esc_html__( 'Center', 'edupro' ),
				'right'  => esc_html__( 'Right', 'edupro' ),
			),
			'multiple' => false,
			'std'      => 'left',
			'tab'      => 'woo-archive',
		),
		array(
			'name' => esc_html__( 'Colors', 'edupro' ),
			'type' => 'heading',
			'tab'  => 'woo-archive',
		),
		array(
			'name' => esc_html__( 'Overlay Color', 'edupro' ),
			'id'   => 'product_overlay_color',
			'type' => 'color',
			'std'  => '',
			'tab'  => 'woo-archive',

		),
		array(
			'name'    => esc_html__( 'Overlay Opacity', 'edupro' ),
			'id'      => 'product_overlay_opacity',
			'type'    => 'select',
			'options' => array(
				'0.05' => '0.05',
				'0.1'  => '0.1',
				'0.15' => '0.15',
				'0.2'  => '0.2',
				'0.25' => '0.25',
				'0.3'  => '0.3',
				'0.35' => '0.35',
				'0.4'  => '0.4',
				'0.45' => '0.45',
				'0.5'  => '0.5',
				'0.55' => '0.55',
				'0.6'  => '0.6',
				'0.65' => '0.65',
				'0.7'  => '0.7',
				'0.75' => '0.75',
				'0.8'  => '0.8',
				'0.85' => '0.85',
				'0.9'  => '0.9',
				'0.95' => '0.95',
				'1'    => '1',
			),
			'std'     => '0.6',
			'tab'     => 'woo-archive',
		),
		array(
			'name' => esc_html__( 'Title Color', 'edupro' ),
			'id'   => 'product_title_color',
			'type' => 'color',
			'std'  => '',
			'tab'  => 'woo-archive',

		),
		array(
			'name' => esc_html__( 'Title Hover Color', 'edupro' ),
			'id'   => 'product_hover_title_color',
			'type' => 'color',
			'std'  => '',
			'tab'  => 'woo-archive',

		),
		array(
			'name' => esc_html__( 'Price Background Color', 'edupro' ),
			'id'   => 'product_bg_price_color',
			'type' => 'color',
			'std'  => '',
			'tab'  => 'woo-archive',
		),
		array(
			'name' => esc_html__( 'Price Color', 'edupro' ),
			'id'   => 'product_price_color',
			'type' => 'color',
			'std'  => '',
			'tab'  => 'woo-archive',

		),
		array(
			'name' => esc_html__( 'Add To Cart Button Background Color', 'edupro' ),
			'id'   => 'product_bg_addcart',
			'type' => 'color',
			'std'  => '',
			'tab'  => 'woo-archive',
		),
		array(
			'name' => esc_html__( 'Add To Cart Button Hover Background Color', 'edupro' ),
			'id'   => 'product_bg_hover_addcart',
			'type' => 'color',
			'std'  => '',
			'tab'  => 'woo-archive',
		),
		array(
			'name' => esc_html__( 'Add To Cart Button Text Color', 'edupro' ),
			'id'   => 'product_text_color_addcart',
			'type' => 'color',
			'std'  => '',
			'tab'  => 'woo-archive',
		),
		array(
			'name' => esc_html__( 'Add To Cart Button Text Hover Color', 'edupro' ),
			'id'   => 'product__hover_text_color_addcart',
			'type' => 'color',
			'std'  => '',
			'tab'  => 'woo-archive',
		),
		array(
			'name'    => esc_html__( 'Sidebar Layout', 'edupro' ),
			'id'      => 'woo_single_layout',
			'type'    => 'image_select',
			'options' => array(
				'sidebar-left'  => 'http://i.imgur.com/Y2sxQ2R.png',
				'sidebar-right' => 'http://i.imgur.com/h7ONxhz.png',
				'no-sidebar'    => 'http://i.imgur.com/m7oQKvk.png',
			),
			'tab'     => 'woo-single',
			'std'     => 'no-sidebar',
		),
		array(
			'id'   => 'woo_single_hidden_price',
			'name' => esc_html__( 'Hide Price', 'edupro' ),
			'type' => 'checkbox',
			'tab'  => 'woo-single',
		),
		array(
			'id'   => 'woo_single_hidden_rating',
			'name' => esc_html__( 'Hide Star Rating', 'edupro' ),
			'type' => 'checkbox',
			'tab'  => 'woo-single',
		),
		array(
			'id'   => 'woo_single_hidden_description',
			'name' => esc_html__( 'Hide Description', 'edupro' ),
			'type' => 'checkbox',
			'tab'  => 'woo-single',
		),
		array(
			'id'   => 'woo_single_hidden_sku',
			'name' => esc_html__( 'Hide SKU', 'edupro' ),
			'type' => 'checkbox',
			'tab'  => 'woo-single',
		),
		array(
			'id'   => 'woo_single_hidden_categories',
			'name' => esc_html__( 'Hide Categories', 'edupro' ),
			'type' => 'checkbox',
			'tab'  => 'woo-single',
		),
		array(
			'id'   => 'woo_single_hidden_tags',
			'name' => esc_html__( 'Hide Tags', 'edupro' ),
			'type' => 'checkbox',
			'tab'  => 'woo-single',
		),
		array(
			'id'   => 'woo_single_hidden_share',
			'name' => esc_html__( 'Hide Share', 'edupro' ),
			'type' => 'checkbox',
			'tab'  => 'woo-single',
		),
		array(
			'id'   => 'woo_single_hidden_related',
			'name' => esc_html__( 'Hide Related Products', 'edupro' ),
			'type' => 'checkbox',
			'tab'  => 'woo-single',
		),
	),
);
