<?php
/**
 * Add option portfolio.
 */
return array(
	'id'             => 'portfolio',
	'title'          => esc_html__( 'Portfolio', 'edupro' ),
	'settings_pages' => 'theme-options',
	'tab'            => 'portfolio',
	'tabs'           => array(
		'portfolio-archive' => array(
			'label' => esc_html__( 'Archive', 'edupro' ),
			'icon'  => 'dashicons-category',
		),
		'portfolio-single'  => array(
			'label' => esc_html__( 'Single', 'edupro' ),
			'icon'  => 'dashicons-admin-post',
		),
	),
	'tab_style'      => 'box',
	'tab_wrapper'    => true,
	'fields'         => array(
		array(
			'name' => esc_html__( 'Header Image', 'edupro' ),
			'id'   => 'portfolio_header_image',
			'type' => 'file_input',
			'tab'  => 'portfolio-archive',
		),
		array(
			'name' => esc_html__( 'Page Title', 'edupro' ),
			'id'   => 'portfolio_page_title',
			'type' => 'text',
			'std'  => esc_html__( 'Portfolio', 'edupro' ),
			'size' => 100,
			'tab'  => 'portfolio-archive',
		),
		array(
			'name'    => esc_html__( 'Sidebar Layout', 'edupro' ),
			'id'      => 'portfolio_layout',
			'type'    => 'image_select',
			'options' => array(
				'sidebar-left'  => 'http://i.imgur.com/Y2sxQ2R.png',
				'sidebar-right' => 'http://i.imgur.com/h7ONxhz.png',
				'no-sidebar'    => 'http://i.imgur.com/m7oQKvk.png',
			),
			'tab'     => 'portfolio-archive',
			'std'     => 'no-sidebar',
		),
		array(
			'name'    => esc_html__( 'Style', 'edupro' ),
			'id'      => 'portfolio_style',
			'type'    => 'select',
			'options' => array(
				'masonry' => esc_html__( 'Masonry', 'edupro' ),
				'grid'    => esc_html__( 'Grid', 'edupro' ),
			),
			'std'     => 'masonry',
			'tab'     => 'portfolio-archive',
		),
		array(
			'id'   => 'portfolio_hidden_filter',
			'name' => esc_html__( 'Hide Filter', 'edupro' ),
			'type' => 'checkbox',
			'tab'  => 'portfolio-archive',
		),
		array(
			'name' => esc_html__( 'Number Of Projects', 'edupro' ),
			'id'   => 'portfolio_per_page',
			'type' => 'text',
			'std'  => '9',
			'size' => 100,
			'tab'  => 'portfolio-archive',
		),
		array(
			'name'    => esc_html__( 'Columns', 'edupro' ),
			'id'      => 'portfolio_column',
			'type'    => 'select',
			'options' => array(
				'column-2' => '2',
				'column-3' => '3',
				'column-4' => '4',
			),
			'std'     => 'column-3',
			'tab'     => 'portfolio-archive',
		),
		array(
			'name' => esc_html__( 'Text For "All" Item In The Filter', 'edupro' ),
			'id'   => 'portfolio_all_text',
			'type' => 'text',
			'std'  => esc_html__( 'All', 'edupro' ),
			'size' => 100,
			'tab'  => 'portfolio-archive',
		),
		array(
			'id'   => 'portfolio_hidden_categories',
			'name' => esc_html__( 'Hide Post Categories', 'edupro' ),
			'type' => 'checkbox',
			'tab'  => 'portfolio-archive',
		),
		array(
			'id'      => 'portfolio_hidden_icon_link',
			'name'    => esc_html__( 'Hide Link Icon', 'edupro' ),
			'type'    => 'checkbox',
			'tab'     => 'portfolio-archive',
			'visible' => array( 'portfolio_style', '=', 'masonry' ),
		),
		array(
			'name' => esc_html__( 'Colors', 'edupro' ),
			'type' => 'heading',
			'tab'  => 'portfolio-archive',
		),
		array(
			'name'    => esc_html__( 'Overlay Color', 'edupro' ),
			'id'      => 'portfolio_overlay_color',
			'type'    => 'color',
			'std'     => '#000',
			'tab'     => 'portfolio-archive',
			'visible' => array( 'portfolio_style', '=', 'masonry' ),
		),
		array(
			'name'    => esc_html__( 'Overlay Opacity', 'edupro' ),
			'id'      => 'portfolio_overlay_opacity',
			'type'    => 'select',
			'options' => array(
				'0.05' => '0.05',
				'0.1'  => '0.1',
				'0.15' => '0.15',
				'0.2'  => '0.2',
				'0.25' => '0.25',
				'0.3'  => '0.3',
				'0.35' => '0.35',
				'0.4'  => '0.4',
				'0.45' => '0.45',
				'0.5'  => '0.5',
				'0.55' => '0.55',
				'0.6'  => '0.6',
				'0.65' => '0.65',
				'0.7'  => '0.7',
				'0.75' => '0.75',
				'0.8'  => '0.8',
				'0.85' => '0.85',
				'0.9'  => '0.9',
				'0.95' => '0.95',
				'1'    => '1',
			),
			'std'     => '0.6',
			'tab'     => 'portfolio-archive',
			'visible' => array( 'portfolio_style', '=', 'masonry' ),
		),
		array(
			'name'    => esc_html__( 'Project Title Color', 'edupro' ),
			'id'      => 'portfolio_title_color',
			'type'    => 'color',
			'std'     => '#212121',
			'tab'     => 'portfolio-archive',
			'visible' => array( 'portfolio_style', '=', 'masonry' ),
		),
		array(
			'name'    => esc_html__( 'Project Title Hover Color', 'edupro' ),
			'id'      => 'portfolio_hover_title_color',
			'type'    => 'color',
			'std'     => '#7cb342',
			'tab'     => 'portfolio-archive',
			'visible' => array( 'portfolio_style', '=', 'masonry' ),
		),
		array(
			'name'    => esc_html__( 'Categories Color', 'edupro' ),
			'id'      => 'portfolio_cate_color',
			'type'    => 'color',
			'std'     => '#fff',
			'tab'     => 'portfolio-archive',
			'visible' => array( 'portfolio_style', '=', 'masonry' ),
		),
		array(
			'name'    => esc_html__( 'Categories Background Color', 'edupro' ),
			'id'      => 'portfolio_catebg_color',
			'type'    => 'color',
			'std'     => '#7cb342',
			'tab'     => 'portfolio-archive',
			'visible' => array( 'portfolio_style', '=', 'masonry' ),
		),
		array(
			'name'    => esc_html__( 'Background Hover Color', 'edupro' ),
			'id'      => 'portfolio_grid_catebg_color',
			'type'    => 'color',
			'std'     => '#7cb342',
			'tab'     => 'portfolio-archive',
			'visible' => array( 'portfolio_style', '=', 'grid' ),
		),
		array(
			'name'    => esc_html__( 'Text Color', 'edupro' ),
			'id'      => 'portfolio_grid_text_color',
			'type'    => 'color',
			'std'     => '#fff',
			'tab'     => 'portfolio-archive',
			'visible' => array( 'portfolio_style', '=', 'grid' ),
		),
		array(
			'name'    => esc_html__( 'Text Hover Color', 'edupro' ),
			'id'      => 'portfolio_grid_hover_text_color',
			'type'    => 'color',
			'std'     => '#673ab7',
			'tab'     => 'portfolio-archive',
			'visible' => array( 'portfolio_style', '=', 'grid' ),
		),
		array(
			'id'      => 'portfolio_grid_hidden_line',
			'name'    => esc_html__( 'Hide Title Bottom Line On Hover', 'edupro' ),
			'type'    => 'checkbox',
			'tab'     => 'portfolio-archive',
			'visible' => array( 'portfolio_style', '=', 'grid' ),
		),
		array(
			'name'    => esc_html__( 'Sidebar Layout', 'edupro' ),
			'id'      => 'portfolio_content_pos',
			'type'    => 'image_select',
			'options' => array(
				'content-left'  => 'http://i.imgur.com/Y2sxQ2R.png',
				'content-right' => 'http://i.imgur.com/h7ONxhz.png',
			),
			'tab'     => 'portfolio-single',
			'std'     => 'content-right',
		),
		array(
			'name' => esc_html__( 'Project Title Color', 'edupro' ),
			'id'   => 'portfolio_single_title_color',
			'type' => 'color',
			'std'  => '#212121',
			'tab'  => 'portfolio-single',
		),
		array(
			'id'   => 'portfolio_single_hidden_cat',
			'name' => esc_html__( 'Hide Category', 'edupro' ),
			'type' => 'checkbox',
			'tab'  => 'portfolio-single',
		),
		array(
			'id'   => 'portfolio_single_hidden_tag',
			'name' => esc_html__( 'Hide Tags', 'edupro' ),
			'type' => 'checkbox',
			'tab'  => 'portfolio-single',
		),
		array(
			'id'   => 'portfolio_single_hidden_share',
			'name' => esc_html__( 'Hide Share Button', 'edupro' ),
			'type' => 'checkbox',
			'tab'  => 'portfolio-single',
		),
		array(
			'id'   => 'portfolio_single_hidden_nav',
			'name' => esc_html__( 'Hide Next/Prev Navigation', 'edupro' ),
			'type' => 'checkbox',
			'tab'  => 'portfolio-single',
		),
		array(
			'id'      => 'off_uppercase_portfolio_title_na',
			'name'    => esc_html__( 'Turn Off Uppercase For Next/Prev Navigation', 'edupro' ),
			'type'    => 'checkbox',
			'tab'     => 'portfolio-single',
			'visible' => array( 'portfolio_hidden_nav', false ),
		),
		array(
			'name'    => esc_html__( 'Title For Next Navigation', 'edupro' ),
			'id'      => 'portfolio_title_next_nav',
			'type'    => 'text',
			'std'     => esc_html__( 'Previous Portfolio', 'edupro' ),
			'size'    => 100,
			'tab'     => 'portfolio-single',
			'visible' => array( 'portfolio_hidden_nav', false ),
		),
		array(
			'name'    => esc_html__( 'Title For Prev Navigation', 'edupro' ),
			'id'      => 'portfolio_title_prev_nav',
			'type'    => 'text',
			'std'     => esc_html__( 'Next Portfolio', 'edupro' ),
			'size'    => 100,
			'tab'     => 'portfolio-single',
			'visible' => array( 'portfolio_hidden_nav', false ),
		),
		array(
			'id'   => 'portfolio_hidden_related',
			'name' => esc_html__( 'Hide Related Projects', 'edupro' ),
			'type' => 'checkbox',
			'tab'  => 'portfolio-single',
		),
		array(
			'name'    => esc_html__( 'Related Projects Title', 'edupro' ),
			'id'      => 'portfolio_title_related',
			'type'    => 'text',
			'std'     => esc_html__( 'Related Porfolios', 'edupro' ),
			'size'    => 100,
			'tab'     => 'portfolio-single',
			'visible' => array( 'portfolio_hidden_related', false ),
		),
		array(
			'id'      => 'off_uppercase_portfolio_title_rel',
			'name'    => esc_html__( 'Turn Off Uppercase For Related Project Title', 'edupro' ),
			'type'    => 'checkbox',
			'tab'     => 'portfolio-single',
			'visible' => array( 'portfolio_hidden_related', false ),
		),
		array(
			'name'    => esc_html__( 'Number Of Related Projects', 'edupro' ),
			'id'      => 'portfolio_related_per_page',
			'type'    => 'select',
			'options' => array(
				'3'  => '3',
				'6'  => '6',
				'9'  => '9',
				'12' => '12'
			),
			'std'     => '3',
			'tab'     => 'portfolio-single',
			'visible' => array( 'portfolio_hidden_related', false ),
		),
	),
);
