<?php
/**
 * Options courses of theme options.
 */
return array(
	'id'             => 'courses',
	'title'          => esc_html__( 'Courses', 'edupro' ),
	'settings_pages' => 'theme-options',
	'tab'            => 'courses',
	'tabs'           => array(
		'courses-archive' => array(
			'label' => esc_html__( 'Courses Archive', 'edupro' ),
			'icon'  => 'dashicons-category',
		),
		'courses-single'  => array(
			'label' => esc_html__( 'Courses Single', 'edupro' ),
			'icon'  => 'dashicons-admin-post',
		),
	),
	'tab_style'      => 'box',
	'tab_wrapper'    => true,
	'fields'         => array(
		array(
			'name' => esc_html__( 'Header Image', 'edupro' ),
			'id'   => 'courses_header_image',
			'type' => 'file_input',
			'tab'  => 'courses-archive',
		),
		array(
			'name'    => esc_html__( 'Sidebar Layout', 'edupro' ),
			'id'      => 'courses_layout',
			'type'    => 'image_select',
			'options' => array(
				'sidebar-left'  => 'http://i.imgur.com/Y2sxQ2R.png',
				'sidebar-right' => 'http://i.imgur.com/h7ONxhz.png',
				'no-sidebar'    => 'http://i.imgur.com/m7oQKvk.png',
			),
			'tab'     => 'courses-archive',
			'std'     => 'sidebar-left',
		),
		array(
			'name' => esc_html__( 'Page title', 'edupro' ),
			'id'   => 'courses_page_title',
			'type' => 'text',
			'std'  => esc_html__( 'Courses', 'edupro' ),
			'size' => 100,
			'tab'  => 'courses-archive',
		),
		array(
			'id'   => 'courses_hidden_filter',
			'name' => esc_html__( 'Hide Courses Filter', 'edupro' ),
			'type' => 'checkbox',
			'tab'  => 'courses-archive',
		),
		array(
			'name'     => esc_html__( 'Number Of Courses', 'edupro' ),
			'id'       => 'courses_per_page',
			'type'     => 'select',
			'options'  => EduPro_Option::get_list_filter_numbers_courses(),
			'multiple' => false,
			'std'      => '9',
			'tab'      => 'courses-archive',
		),
		array(
			'name'     => esc_html__( 'Style', 'edupro' ),
			'id'       => 'courses_style_default',
			'type'     => 'select',
			'options'  => array(
				'grid' => esc_html__( 'Grid', 'edupro' ),
				'list' => esc_html__( 'List', 'edupro' ),
			),
			'multiple' => false,
			'std'      => 'grid',
			'tab'      => 'courses-archive',
		),
		array(
			'name'     => esc_html__( 'Sort Courses By', 'edupro' ),
			'id'       => 'sort_courses_default',
			'type'     => 'select',
			'options'  => array(
				'trendding' => esc_html__( 'Trending', 'edupro' ),
				'rating'    => esc_html__( 'Rating', 'edupro' ),
				'new'       => esc_html__( 'Date', 'edupro' ),
			),
			'multiple' => false,
			'std'      => 'new',
			'tab'      => 'courses-archive',
		),
		array(
			'id'   => 'courses_hidden_rating',
			'name' => esc_html__( 'Hide Rating', 'edupro' ),
			'type' => 'checkbox',
			'tab'  => 'courses-archive',
		),
		array(
			'id'   => 'courses_hidden_author',
			'name' => esc_html__( 'Hide Author', 'edupro' ),
			'type' => 'checkbox',
			'tab'  => 'courses-archive',
		),
		array(
			'id'      => 'courses_hidden_des',
			'name'    => esc_html__( 'Hide Description', 'edupro' ),
			'type'    => 'checkbox',
			'visible' => array( 'courses_style_default', '=', 'list' ),
			'tab'     => 'courses-archive',
		),
		array(
			'id'   => 'courses_hidden_count_total_user',
			'name' => esc_html__( 'Hide Total User', 'edupro' ),
			'type' => 'checkbox',
			'tab'  => 'courses-archive',
		),
		array(
			'id'   => 'courses_hidden_number_total_comment',
			'name' => esc_html__( 'Hide Total Comment', 'edupro' ),
			'type' => 'checkbox',
			'tab'  => 'courses-archive',
		),
		array(
			'id'   => 'courses_hidden_price',
			'name' => esc_html__( 'Hide Price', 'edupro' ),
			'type' => 'checkbox',
			'tab'  => 'courses-archive',
		),
		array(
			'name'     => esc_html__( 'Page Navigation Alignment', 'edupro' ),
			'id'       => 'courses_paging_align',
			'type'     => 'select',
			'options'  => array(
				'left'   => esc_html__( 'Left', 'edupro' ),
				'center' => esc_html__( 'Center', 'edupro' ),
				'right'  => esc_html__( 'Right', 'edupro' ),
			),
			'multiple' => false,
			'std'      => 'left',
			'tab'      => 'courses-archive',
		),

		// Color
		array(
			'name' => esc_html__( 'Color', 'edupro' ),
			'type' => 'heading',
			'tab'  => 'courses-archive',
		),
		array(
			'name' => esc_html__( 'Title Color', 'edupro' ),
			'id'   => 'course_title_color',
			'type' => 'color',
			'std'  => '',
			'tab'  => 'courses-archive',
		),
		array(
			'name' => esc_html__( 'Title Hover Color', 'edupro' ),
			'id'   => 'course_hover_title_color',
			'type' => 'color',
			'std'  => '',
			'tab'  => 'courses-archive',
		),
		array(
			'name' => esc_html__( 'Author Name Color', 'edupro' ),
			'id'   => 'course_author_color',
			'type' => 'color',
			'std'  => '',
			'tab'  => 'courses-archive',
		),
		array(
			'name' => esc_html__( 'Author Link Color', 'edupro' ),
			'id'   => 'course_author_link_color',
			'type' => 'color',
			'std'  => '',
			'tab'  => 'courses-archive',
		),
		array(
			'name' => esc_html__( 'Author Link Hover Color', 'edupro' ),
			'id'   => 'course_hover_author_link_color',
			'type' => 'color',
			'std'  => '',
			'tab'  => 'courses-archive',
		),
		array(
			'name' => esc_html__( 'Users & Comments Color', 'edupro' ),
			'id'   => 'course_meta_color',
			'type' => 'color',
			'std'  => '',
			'tab'  => 'courses-archive',
		),
		array(
			'name' => esc_html__( 'Price Button Background Color', 'edupro' ),
			'id'   => 'course_price_color',
			'type' => 'color',
			'std'  => '',
			'tab'  => 'courses-archive',
		),
		array(
			'name' => esc_html__( 'Price Button Background Hover Color', 'edupro' ),
			'id'   => 'hover_course_price_color',
			'type' => 'color',
			'std'  => '',
			'tab'  => 'courses-archive',
		),
		array(
			'name' => esc_html__( 'Free/Open Button Background Color', 'edupro' ),
			'id'   => 'course_free_color',
			'type' => 'color',
			'std'  => '',
			'tab'  => 'courses-archive',
		),
		array(
			'name' => esc_html__( 'Button Free/Open Background Hover Color', 'edupro' ),
			'id'   => 'hover_course_free_color',
			'type' => 'color',
			'std'  => '',
			'tab'  => 'courses-archive',
		),
		array(
			'name' => esc_html__( 'Button Text Color', 'edupro' ),
			'id'   => 'txt_btn_course_color',
			'type' => 'color',
			'std'  => '',
			'tab'  => 'courses-archive',
		),
		array(
			'name'    => esc_html__( 'Sidebar Layout', 'edupro' ),
			'id'      => 'courses_single_layout',
			'type'    => 'image_select',
			'options' => array(
				'sidebar-left'  => 'http://i.imgur.com/Y2sxQ2R.png',
				'sidebar-right' => 'http://i.imgur.com/h7ONxhz.png',
				'no-sidebar'    => 'http://i.imgur.com/m7oQKvk.png',
			),
			'tab'     => 'courses-single',
			'std'     => 'sidebar-right',
		),
		array(
			'id'   => 'courses_single_hidden_curriculum',
			'name' => esc_html__( 'Hide Curriculum', 'edupro' ),
			'type' => 'checkbox',
			'tab'  => 'courses-single',
		),
		array(
			'id'   => 'courses_single_hidden_instructor',
			'name' => esc_html__( 'Hide Instructor', 'edupro' ),
			'type' => 'checkbox',
			'tab'  => 'courses-single',
		),
		array(
			'id'   => 'courses_single_hidden_review',
			'name' => esc_html__( 'Hide Review', 'edupro' ),
			'type' => 'checkbox',
			'tab'  => 'courses-single',
		),
		array(
			'id'      => 'courses_single_hidden_listcomment',
			'name'    => esc_html__( 'Hide List Comment', 'edupro' ),
			'type'    => 'checkbox',
			'tab'     => 'courses-single',
			'visible' => array( 'courses_single_hidden_review', false ),
		),
		array(
			'id'   => 'courses_hidden_related',
			'name' => esc_html__( 'Hide Related Courses', 'edupro' ),
			'type' => 'checkbox',
			'tab'  => 'courses-single',
		),
		array(
			'name'    => esc_html__( 'Related Courses Title', 'edupro' ),
			'id'      => 'courses_title_related',
			'type'    => 'text',
			'std'     => esc_html__( 'Related Courses', 'edupro' ),
			'size'    => 100,
			'tab'     => 'courses-single',
			'visible' => array( 'courses_hidden_related', false ),
		),
		array(
			'name'    => esc_html__( 'Number Of Related Courses', 'edupro' ),
			'id'      => 'courses_related_per_page',
			'type'    => 'select',
			'options' => array(
				'4'  => '4',
				'8'  => '8',
				'12'  => '12',
			),
			'std'     => '3',
			'tab'     => 'courses-single',
			'visible' => array( 'courses_hidden_related', false ),
		),
	),
);
