<?php

/**
 * Customizer general css
 */
function edupro_customizer_general() {
	$css = '';
	if ( get_theme_mod( 'edupro_font_for_title' ) && 'Roboto Condensed, 300:300italic:regular:italic:700:700italic, sans-serif' != get_theme_mod( 'edupro_font_for_title' ) ) {
		$font_family_title     = get_theme_mod( 'edupro_font_for_title' );
		$font_family_title_end = $font_family_title;
		if ( ! in_array( $font_family_title, edupro_font_browser() ) ) {
			$font_family_title     = str_replace( '"', '', $font_family_title );
			$font_title_explo      = explode( ", ", $font_family_title );
			$font_title            = $font_title_explo[0];
			$font_title_type       = $font_title_explo[1];
			$font_title_serif      = $font_title_explo[2];
			$font_title_type       = str_replace( ':', ',', $font_title_type );
			$title_font_replace    = str_replace( ' ', '+', $font_title );
			$font_family_title_end = "'" . $font_title . "', " . $font_title_serif;

			$css .= '@import url(//fonts.googleapis.com/css?family=' . sanitize_text_field( $title_font_replace ) . ':' . sanitize_text_field( $font_title_type ) . ');';
		}

		$css .= '
		h1, 
		h2, 
		h3, 
		h4, 
		h5, 
		h6, 
		.widget-title,
		.site-header a,
		.edupro_widget_recent_courses .widget__recent_title_courses a,
		.courses-content .widget__latest_events .widget__latest_title_events a,
		.jetpack_subscription_widget #subscribe-email input,
		body #page.site .footer-widgets a,
		.icon-box .icon-box__title,
		.page__title h1,
		#comments .comment-respond .comment-reply-title,
		.edupro-comments-title,
		.page__title,
		.single-post .single__content .entry-title,
		.archive .featured-course .featured-course__text h3 a,
		.single__event-content .event_heading__title,
		.ctf7__sidebar .ctf7-title h3,
		.header--s3 .main-navigation,
		.single .single__box,
		.single-sfwd-courses .main__content-courses .nav-tabs > li > a,
		.shop__woocommerce ul.products li.product h3,
		.woocommerce.single-product .summary .product_title,
		.woocommerce div.product .woocommerce-tabs ul.tabs li a,
		.featured-courses--s2 .featured-course__text h3 a,
		.featured-events--s2 .featured-event .featured-event__text h3 a,
		.featured-events--s2 .featured-event.short-style .featured-event__text h3 a,
		.register__form__3 .title__register__form h3,
		.featured-posts--s2 .lastest-news__text h3 a,
		.featured-courses--s3 .featured-course__text h3 a,
		.featured-events--s3 .featured-event__text h3 a,
		.featured-posts--s1 .featured-post__text h3 a,
		.popular_courses_big .item.popular_courses_s2 h3 a,
		.featured-events--s5 .featured-event .featured-event__thumb .featured-event__text h3 a,
		.featured-posts--s4 .lastest-news .lastest-news__text h3 a,
		.popular_courses_big .item.popular_courses_s1 .popular_courses_s1__text h3 a,
		.site .jetpack_subscription_widget #subscribe-submit input,
		.site .featured-events--s4 .featured-event .featured-event__date .featured-event__month,
		.site  .featured-events--s4 .featured-event .featured-event__date .featured-event__day,
		.site  .featured-events--s4 .featured-event .featured-event__date .featured-event__year,
		.site .featured-events--s4 .featured-event .featured-event__date,
		.featured-events--s4 .featured-event .featured-event__text h3 a,
		.featured-courses--s4 .featured-course .featured-course__wrap .featured-course__text h3 a,
		.featured-courses--s6 .featured-course__text h3 a,
		.featured-courses--s5 .featured-course .featured-course__text h3 a,
		.counter_up .counter_text,
		.featured-events--s1 .featured-event__text h3,
		.main-navigation a,
		body #page.site .site-header .main-navigation >ul.menu >li > .sub-menu li a,
		body #page.site .site-header .main-navigation >ul.menu >li > a, 
		.mobile-sidebar .primary-menu-mobile a,
		.woocommerce.single-product .summary .product_meta .product-meta-title,
		.woocommerce.single-product .related h2,
		.tags-links strong,
		.single-post .main__content__author .author__info h3,
		.main__content__related-posts .section-title,
		.archive .grid-main .featured-event__text h3 a,
		.archive .grid-main .featured-event__day,
		.archive .grid-main .featured-event__date,
		.archive .grid-main .featured-event__month,
		.widget-subtitle,
		.sidebar-single .inline .featured-course__meta a,
		.sidebar-single .inline.author__infomation .author__infomation-details .author__infomation-name,
		.sidebar-single .widget-title,
		.sidebar-single .inline.course-relation__infomation .sidebar-single__title,
		.sidebar-single .inline.course-relation__infomation .sidebar-single__title span,
		.widget__courses-relation .course-relation__infomation__item .excrept a,
		.single-sfwd-courses .single__video .single__video-thumblist .single__video-list .thumb-video .topic__title a,
		.single .single__head.bg-dark .page__title,
		.single-sfwd-courses #lesson_heading h4 a,
		.widget__filter-courses .widget-subtitle,
		.single-jetpack-portfolio .jetpack-portfolio .portfolio-meta label,
		.single-jetpack-portfolio .portfolio__related .portfolio__related-title,
		.featured-courses--s1 .featured-course__text h3,
		.featured-events--s1 .featured-event__date,
		.testimonials--s4 .testimonial__author,
		.single-jetpack-portfolio .jetpack-portfolio .page-title,
		.projects.masonry .project .project__title a,
		.single-event h3,
		.share-event strong,
		.event__info h4,
		#page.site .blog__content .blog__content__info .title a,
		.single .single__head .page__title,
		.single-sfwd-courses .single__head .page__title,
		.login__form h3,
		.testimonials--s1 .testimonial__author { font-family:' . sanitize_text_field( $font_family_title_end ) . '; font-weight: normal; }';
	}

	if ( get_theme_mod( 'edupro_font_for_body' ) && 'Roboto, 100:100italic:300:300italic:regular:italic:500:500italic:700:700italic:900:900italic, sans-serif' != get_theme_mod( 'edupro_font_for_body' ) ) {
		$font_family_title     = get_theme_mod( 'edupro_font_for_body' );
		$font_family_title_end = $font_family_title;
		if ( ! in_array( $font_family_title, edupro_font_browser() ) ) {
			$font_family_title     = str_replace( '"', '', $font_family_title );
			$font_title_explo      = explode( ", ", $font_family_title );
			$font_title            = $font_title_explo[0];
			$font_title_type       = $font_title_explo[1];
			$font_title_serif      = $font_title_explo[2];
			$font_title_type       = str_replace( ':', ',', $font_title_type );
			$title_font_replace    = str_replace( ' ', '+', $font_title );
			$font_family_title_end = "'" . $font_title . "', " . $font_title_serif;

			$css .= '@import url(//fonts.googleapis.com/css?family=' . sanitize_text_field( $title_font_replace ) . ':' . sanitize_text_field( $font_title_type ) . ');';
		}

		$css .= 'body, 
		button, 
		input, 
		select,
		textarea, 
		#respond textarea, 
		.widget input[type="text"], 
		.widget input[type="email"], 
		.widget input[type="date"], 
		.widget input[type="number"], 
		.wpcf7 textarea,
		.mc4wp-form input, 
		#respond input, 
		.wpcf7 input, 
		#searchform input.search-input, 
		ul.homepage-featured-boxes .penci-fea-in h4, 
		.widget.widget_categories ul li span.category-item-count,
		.header-slogan .header-slogan-text, 
		.about-widget .about-me-heading, 
		.widget ul.side-newsfeed li .side-item .side-item-text .side-item-meta,
		.widget .cat-item a,
		#wp-calendar tbody td,
		.footer-widgets a,
		.widget_rss .rss-date, 
		.tagcloud a,
		#colophon .site-info,
		.widget_rss cite,
		body .site#page .blog__content .blog__content__date .date,
		body #page.site .topbar ul.menu li a,
		body #page.site .topbar .edupro-link-login ul li a,
		.site .widget_archive li,
		.footer-widgets select,
		.page__banner-top .breadcrumbs,
		.widget__latest_posts .widget__latest_title_posts a,
		.widget select,
		.site #comments #submit,
		.single__banner-top .single__breadcrumbs,
		#learndash_lessons a, 
		#learndash_quizzes a, 
		.expand_collapse a, 
		.learndash_topic_dots a, 
		.learndash_topic_dots a > span, 
		#learndash_lesson_topics_list span a, 
		#learndash_profile a, 
		#learndash_profile a span,
		#learndash_lessons #lesson_heading, 
		#learndash_profile .learndash_profile_heading, 
		#learndash_quizzes #quiz_heading, 
		#learndash_lesson_topics_list div > strong,
		.content-posts #infinite-handle span,
		body #page.site .main__sidebar a,
		.content-list .blog__content .blog__content__info ul li,
		.ctf7__sidebar .ctf7-content .wpcf7 .wpcf7-submit,
		.single .single__box > div p,
		.error-404 .page-title,
		.shop__woocommerce ul.products li.product .add_to_cart_button, 
		.shop__woocommerce ul.products li.product .ajax_add_to_cart,
		.shop__woocommerce ul.products li.product .amount,
		.woocommerce nav.woocommerce-pagination ul.page-numbers li a, 
		.woocommerce nav.woocommerce-pagination ul.page-numbers li span,
		#comments #submit:hover, .woocommerce #review_form #respond .form-submit #submit,
		.shop__woocommerce .sidebar__woocommerce .cart_list li a, 
		.shop__woocommerce .sidebar__woocommerce .product_list_widget li a,
		.wpcf7 .submit input,
		.featured-events--s2 .featured-event .featured-event__day,
		.featured-events--s2 .featured-event .featured-event_summary p,
		.featured-events--s2 .featured-event.short-style .featured-event__day,
		.featured-events--s2 .featured-event.short-style .featured-event__month,
		.pricing_no_link,
		.button,
		.site .testimonials_home-main-new .testimonial__content p,
		.featured-events--s5 .featured-event .featured-event__thumb .featured-event__date .featured-event__day,
		.featured-events--s5 .featured-event .featured-event__thumb .featured-event__date .featured-event__month,
		.register__form__3 #registration .button,
		.register__form__4 #registration .button,
		.search_course__3 form input,
		.featured-courses--s5 .featured-course .featured-course__info a,
		.edupro-login-container .edupro-login input[type="submit"],
		.login__form .login__form__login-submit input,
		.login__form .login__form__register-now p,
		#comments label, .woocommerce #review_form #respond .form-submit label,
		.main__content__pre__next h3 a,
		.single__content .blog__content__info, 
		.single__content .blog__content__info a,
		.archive .content__event .content__event__container .content__event__wrap .content__event__wrap__joinnow a,
		.tags-links a,
		.projects.grid .project .project__title,
		.event__info .event__info__meta,
		#page.site .blog__content .blog__content__info ul li a { font-family: ' . sanitize_text_field( $font_family_title_end ) . ' }';
	}

	$body_size = get_theme_mod( 'edupro_font_for_size_body' );

	if ( is_numeric( $body_size ) && $body_size > 1 && $body_size != '15' ) {
		$css .= 'body, 
		button, 
		input, 
		select,
		textarea, 
		#respond textarea, 
		.widget input[type="text"], 
		.widget input[type="email"], 
		.widget input[type="date"], 
		.widget input[type="number"],
		.single-jetpack-portfolio .jetpack-portfolio .entry-content p { font-size: ' . absint( $body_size ) . 'px; line-height: 1.8; }';
	}

	if ( get_theme_mod( 'edupro_font_weight_title' ) && ( get_theme_mod( 'edupro_font_weight_title' ) != 'normal' ) ) {

		$css .= 'h1, 
		h2, 
		h3, 
		h4, 
		h5, 
		h6, 
		.widget-title,
		.site-header a,
		.edupro_widget_recent_courses .widget__recent_title_courses a,
		.courses-content .widget__latest_events .widget__latest_title_events a,
		.jetpack_subscription_widget #subscribe-email input,
		body #page.site .footer-widgets a,
		.icon-box .icon-box__title,
		.page__title h1,
		#comments .comment-respond .comment-reply-title,
		.edupro-comments-title,
		.page__title,
		.single-post .single__content .entry-title,
		.archive .featured-course .featured-course__text h3 a,
		.single__event-content .event_heading__title,
		.ctf7__sidebar .ctf7-title h3,
		.header--s3 .main-navigation,
		.single .single__box,
		.single-sfwd-courses .main__content-courses .nav-tabs > li > a,
		.shop__woocommerce ul.products li.product h3,
		.woocommerce.single-product .summary .product_title,
		.woocommerce div.product .woocommerce-tabs ul.tabs li a,
		.featured-courses--s2 .featured-course__text h3 a,
		.featured-events--s2 .featured-event .featured-event__text h3 a,
		.featured-events--s2 .featured-event.short-style .featured-event__text h3 a,
		.register__form__3 .title__register__form h3,
		.featured-posts--s2 .lastest-news__text h3 a,
		.featured-courses--s3 .featured-course__text h3 a,
		.featured-events--s3 .featured-event__text h3 a,
		.featured-posts--s1 .featured-post__text h3 a,
		.popular_courses_big .item.popular_courses_s2 h3 a,
		.featured-events--s5 .featured-event .featured-event__thumb .featured-event__text h3 a,
		.featured-posts--s4 .lastest-news .lastest-news__text h3 a,
		.popular_courses_big .item.popular_courses_s1 .popular_courses_s1__text h3 a,
		.site .jetpack_subscription_widget #subscribe-submit input,
		.site .featured-events--s4 .featured-event .featured-event__date .featured-event__month,
		.site .featured-events--s4 .featured-event .featured-event__date .featured-event__day,
		.site .featured-events--s4 .featured-event .featured-event__date .featured-event__year,
		.site .featured-events--s4 .featured-event .featured-event__date,
		.site .featured-events--s4 .featured-event .featured-event__text h3 a,
		.featured-courses--s4 .featured-course .featured-course__wrap .featured-course__text h3 a,
		.featured-courses--s6 .featured-course__text h3 a,
		.featured-courses--s5 .featured-course .featured-course__text h3 a,
		.counter_up .counter_text,
		.featured-events--s1 .featured-event__text h3,
		.main-navigation a,
		body #page.site .site-header .main-navigation >ul.menu >li > .sub-menu li a,
		body #page.site .site-header .main-navigation >ul.menu >li > a, 
		.mobile-sidebar .primary-menu-mobile a,
		.woocommerce.single-product .summary .product_meta .product-meta-title,
		.woocommerce.single-product .related h2,
		.tags-links strong,
		.single-post .main__content__author .author__info h3,
		.main__content__related-posts .section-title,
		.archive .grid-main .featured-event__text h3 a,
		.archive .grid-main .featured-event__day,
		.archive .grid-main .featured-event__date,
		.archive .grid-main .featured-event__month,
		.widget-subtitle,
		.sidebar-single .inline .featured-course__meta a,
		.sidebar-single .inline.author__infomation .author__infomation-details .author__infomation-name,
		.sidebar-single .widget-title,
		.sidebar-single .inline.course-relation__infomation .sidebar-single__title,
		.sidebar-single .inline.course-relation__infomation .sidebar-single__title span,
		.widget__courses-relation .course-relation__infomation__item .excrept a,
		.single-sfwd-courses .single__video .single__video-thumblist .single__video-list .thumb-video .topic__title a,
		.single .single__head.bg-dark .page__title,
		.single-sfwd-courses #lesson_heading h4 a,
		.widget__filter-courses .widget-subtitle,
		.single-jetpack-portfolio .jetpack-portfolio .portfolio-meta label,
		.single-jetpack-portfolio .portfolio__related .portfolio__related-title,
		.featured-courses--s1 .featured-course__text h3,
		.featured-events--s1 .featured-event__date,
		.testimonials--s4 .testimonial__author,
		.single-jetpack-portfolio .jetpack-portfolio .page-title,
		.projects.masonry .project .project__title a,
		.single-event h3,
		.share-event strong,
		.event__info h4,
		#page.site .blog__content .blog__content__info .title a,
		.single .single__head .page__title,
		.single-sfwd-courses .single__head .page__title,
		.login__form h3,
		.testimonials--s1 .testimonial__author { font-weight: ' . get_theme_mod( 'edupro_font_weight_title' ) . '; }';

	}


	return $css;
}